from __future__ import annotations

import pathlib
from typing import Literal, Optional

import yaml
from pydantic import BaseModel, Field, field_validator, model_validator

ProviderName = Literal["openai"]


class Settings(BaseModel):
    target_model: str = "gpt-4o"
    judge_model: str = "gpt-4o-mini"


class TestCase(BaseModel):
    name: str = Field(..., min_length=1)
    prompt: str = Field(..., min_length=1)
    system: Optional[str] = None
    rules: list[str] = Field(..., min_length=1)
    provider: Optional[ProviderName] = None
    model: Optional[str] = None
    judge_model: Optional[str] = None

    @field_validator("rules")
    @classmethod
    def validate_rules(cls, v: list[str]) -> list[str]:
        for r in v:
            if not r.strip():
                raise ValueError("rule must not be empty")
        return v


class CrilioConfig(BaseModel):
    provider: Optional[ProviderName] = None
    model: Optional[str] = None
    judge_model: Optional[str] = None
    base_url: Optional[str] = None
    system: Optional[str] = None
    settings: Optional[Settings] = None
    tests: list[TestCase] = Field(..., min_length=1)

    @field_validator("tests")
    @classmethod
    def validate_tests(cls, v: list[TestCase]) -> list[TestCase]:
        names = [t.name for t in v]
        if len(names) != len(set(names)):
            raise ValueError("test names must be unique")
        return v

    @model_validator(mode="after")
    def _normalize_settings(self):
        if self.settings:
            if not self.model:
                self.model = self.settings.target_model
            if not self.judge_model:
                self.judge_model = self.settings.judge_model
            if not self.provider:
                self.provider = "openai"
        if not self.model and self.provider == "openai":
            self.model = "gpt-4o-mini"
        if not self.judge_model:
            self.judge_model = self.model or "gpt-4o-mini"
        return self


def load_config(path: str | pathlib.Path) -> CrilioConfig:
    p = pathlib.Path(path)
    if not p.exists():
        raise FileNotFoundError(f"config not found: {p}")
    raw = yaml.safe_load(p.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError("crilio.yaml must be a mapping")
    if "tests" not in raw:
        raise ValueError("crilio.yaml missing required key: 'tests'")
    if "settings" in raw and isinstance(raw["settings"], dict):
        s = raw["settings"]
        if "target_model" in s and "model" not in raw:
            raw["model"] = s["target_model"]
        if "judge_model" in s and "judge_model" not in raw:
            raw["judge_model"] = s["judge_model"]
        if "provider" not in raw:
            raw["provider"] = "openai"
    return CrilioConfig.model_validate(raw)


def dump_yaml(cfg: CrilioConfig) -> str:
    data: dict = {}
    target_model = cfg.model or (cfg.settings.target_model if cfg.settings else "gpt-4o")
    judge_model = cfg.judge_model or (cfg.settings.judge_model if cfg.settings else "gpt-4o-mini")
    data["settings"] = {
        "target_model": target_model,
        "judge_model": judge_model,
    }
    if cfg.system:
        data["system"] = cfg.system
    data["tests"] = [t.model_dump(exclude_none=True) for t in cfg.tests]
    header = "# crilio.yaml\n# Generated by `crilio init` — edit to match your app\n\n"
    return header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


DEFAULT_CONFIG_YAML = """\
# crilio.yaml
settings:
  target_model: "gpt-4o"
  judge_model: "gpt-4o-mini"

tests:
  - name: "Refund Policy Check"
    prompt: "How long do I have to return a product?"
    rules:
      - "Must mention the 30-day return window."
      - "Must NOT mention competitor names."

  - name: "JSON Format Check"
    prompt: |
      Return ONLY this JSON and nothing else: {"status": "shipped", "order_id": "12345"}
    rules:
      - "Must return valid JSON with keys 'status' and 'order_id'."
      - "Must NOT include apologies or extra prose."
"""
